# Generated by Django 3.0.6 on 2020-07-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('age', models.CharField(choices=[('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], max_length=2)),
                ('failures', models.CharField(choices=[('0', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', 'More than 4')], max_length=1)),
                ('pstatus', models.CharField(choices=[('A', 'Apart'), ('T', 'together')], max_length=1)),
                ('dalc', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Average'), ('4', 'High'), ('5', 'Very High')], max_length=1)),
                ('higher', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('famrel', models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Neutral'), ('4', 'Good'), ('5', 'Very Good')], max_length=1)),
                ('G1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('G2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
