# Generated by Django 3.0.6 on 2020-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmodel',
            name='G3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
